name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: docker.io
  USERNAME: srijashenkeshi5
  IMAGE_NAME: srijashenkeshi5/demo-cloud-run-app
  IMAGE_TAG: ${{ github.run_number }}
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Make gradlew executable 
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: generate container image
      run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

    - name: Docker ls 
      run: docker images

    - name: Log in to the Container registry 
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ env.USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Push docker image to Docker Hub
      run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      

